import { useMemo, useState } from "react"
import { AlertCircle } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Switch } from "@/components/ui/switch"
import { Textarea } from "@/components/ui/textarea"
import { CopyButton } from "@/components/tool/CopyButton"
import { DownloadButton } from "@/components/tool/DownloadButton"

type JsonValue =
  string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue }

/** Initialisms Go style guide wants fully capitalised in exported names. */
const INITIALISMS = new Set([
  "ACL",
  "API",
  "ASCII",
  "CPU",
  "CSS",
  "DNS",
  "EOF",
  "GUID",
  "HTML",
  "HTTP",
  "HTTPS",
  "ID",
  "IP",
  "JSON",
  "LHS",
  "QPS",
  "RAM",
  "RHS",
  "RPC",
  "SLA",
  "SMTP",
  "SQL",
  "SSH",
  "TCP",
  "TLS",
  "TTL",
  "UDP",
  "UI",
  "UID",
  "UUID",
  "URI",
  "URL",
  "UTF8",
  "VM",
  "XML",
  "XSRF",
  "XSS",
])

function toGoName(key: string): string {
  const parts = key
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)

  if (parts.length === 0) return "Field"

  const name = parts
    .map((part) => {
      const upper = part.toUpperCase()
      if (INITIALISMS.has(upper)) return upper
      return part.charAt(0).toUpperCase() + part.slice(1).toLowerCase()
    })
    .join("")

  return /^[0-9]/.test(name) ? `_${name}` : name
}

function isPlainObject(value: JsonValue): value is { [key: string]: JsonValue } {
  return typeof value === "object" && value !== null && !Array.isArray(value)
}

/**
 * Widens two inferred Go types into one that can hold both. Used when the
 * elements of an array disagree, which JSON allows and Go does not.
 */
function mergeTypes(a: string | null, b: string): string {
  if (a === null || a === b) return b
  if ((a === "int" && b === "float64") || (a === "float64" && b === "int"))
    return "float64"
  return "interface{}"
}

function numberType(value: number): string {
  return Number.isInteger(value) ? "int" : "float64"
}

interface RenderOptions {
  omitempty: boolean
  indent: string
}

function renderStruct(
  entries: [string, JsonValue][],
  depth: number,
  options: RenderOptions,
): string {
  const pad = options.indent.repeat(depth + 1)
  const used = new Map<string, number>()

  const lines = entries.map(([key, value]) => {
    let name = toGoName(key)
    const seen = used.get(name)
    if (seen !== undefined) {
      used.set(name, seen + 1)
      name = `${name}${seen + 1}`
    } else {
      used.set(name, 0)
    }

    const tag = options.omitempty ? `${key},omitempty` : key
    const type = goType(value, depth + 1, options)
    return `${pad}${name} ${type} \`json:"${tag}"\``
  })

  return `struct {\n${lines.join("\n")}\n${options.indent.repeat(depth)}}`
}

/** Collects the union of keys across every object in an array, in first-seen order. */
function mergeObjects(items: JsonValue[]): [string, JsonValue][] {
  const merged = new Map<string, JsonValue>()

  for (const item of items) {
    if (!isPlainObject(item)) continue
    for (const [key, value] of Object.entries(item)) {
      const existing = merged.get(key)
      if (existing === undefined || existing === null) {
        merged.set(key, value)
      } else if (
        typeof existing === "number" &&
        typeof value === "number" &&
        !Number.isInteger(value)
      ) {
        merged.set(key, value)
      }
    }
  }

  return [...merged.entries()]
}

function goType(value: JsonValue, depth: number, options: RenderOptions): string {
  if (value === null) return "interface{}"
  if (typeof value === "string") return "string"
  if (typeof value === "boolean") return "bool"
  if (typeof value === "number") return numberType(value)

  if (Array.isArray(value)) {
    if (value.length === 0) return "[]interface{}"

    if (value.every(isPlainObject)) {
      return `[]${renderStruct(mergeObjects(value), depth, options)}`
    }

    let element: string | null = null
    for (const item of value) {
      element = mergeTypes(element, goType(item, depth, options))
    }
    return `[]${element ?? "interface{}"}`
  }

  return renderStruct(Object.entries(value), depth, options)
}

function convert(json: string, rootName: string, omitempty: boolean): string {
  const parsed = JSON.parse(json) as JsonValue
  const options: RenderOptions = { omitempty, indent: "\t" }
  const name = toGoName(rootName) || "AutoGenerated"

  if (Array.isArray(parsed)) {
    return `type ${name} ${goType(parsed, 0, options)}\n`
  }

  if (!isPlainObject(parsed)) {
    return `type ${name} ${goType(parsed, 0, options)}\n`
  }

  return `type ${name} ${renderStruct(Object.entries(parsed), 0, options)}\n`
}

const SAMPLE = `{
  "user_id": 42,
  "name": "Ada",
  "is_active": true,
  "score": 91.5,
  "profile": { "url": "https://example.com", "followers": 1200 },
  "tags": ["go", "json"]
}`

export default function JsonToGo() {
  const [input, setInput] = useState(SAMPLE)
  const [rootName, setRootName] = useState("AutoGenerated")
  const [omitempty, setOmitempty] = useState(false)

  const { output, error } = useMemo(() => {
    if (!input.trim()) return { output: "", error: null }
    try {
      return { output: convert(input, rootName, omitempty), error: null }
    } catch (cause) {
      const message =
        cause instanceof Error ? cause.message : "Could not parse this JSON."
      return { output: "", error: message }
    }
  }, [input, rootName, omitempty])

  return (
    <div className="space-y-5">
      <div className="grid gap-4 sm:grid-cols-2">
        <div>
          <Label htmlFor="go-root-name">Root type name</Label>
          <Input
            id="go-root-name"
            name="rootName"
            value={rootName}
            onChange={(event) => setRootName(event.target.value)}
            placeholder="AutoGenerated"
            className="mt-1.5"
            spellCheck={false}
          />
        </div>
        <div className="flex items-center gap-2 sm:self-end sm:pb-2">
          <Switch
            id="go-omitempty"
            name="omitempty"
            checked={omitempty}
            onCheckedChange={setOmitempty}
          />
          <Label htmlFor="go-omitempty" className="font-normal">
            Add omitempty to every tag
          </Label>
        </div>
      </div>

      <div className="grid gap-4 lg:grid-cols-2">
        <div>
          <Label htmlFor="go-json-input">JSON</Label>
          <Textarea
            id="go-json-input"
            name="json"
            value={input}
            onChange={(event) => setInput(event.target.value)}
            placeholder="Paste a JSON response or object."
            className="mt-1.5 min-h-72 resize-y font-mono text-sm"
            spellCheck={false}
            aria-invalid={error ? true : undefined}
          />
        </div>
        <div>
          <Label htmlFor="go-output">Go struct</Label>
          <Textarea
            id="go-output"
            name="result"
            value={output}
            readOnly
            placeholder="The generated type appears here."
            className="bg-muted/40 mt-1.5 min-h-72 resize-y font-mono text-sm"
            spellCheck={false}
          />
        </div>
      </div>

      {error && (
        <div className="border-destructive/30 bg-destructive/10 text-destructive flex items-start gap-2 rounded-lg border p-3 text-sm">
          <AlertCircle className="mt-0.5 size-4 shrink-0" />
          <span>{error}</span>
        </div>
      )}

      <div className="flex flex-wrap gap-2">
        <CopyButton value={output} label="Copy struct" />
        <DownloadButton
          getBlob={() => new Blob([output], { type: "text/plain" })}
          filename="types.go"
          disabled={!output}
        />
        <Button variant="outline" size="sm" onClick={() => setInput("")}>
          Clear
        </Button>
      </div>
    </div>
  )
}
