import { ScanEye } from "lucide-react"
import type { ToolMeta } from "@/types/tool"

const meta: ToolMeta = {
  slug: "invisible-character-remover",
  title: "Invisible Character Remover",
  description:
    "Find and strip zero-width spaces, smart quotes, and other hidden characters from text.",
  longDescription:
    "Paste text to reveal every character that does not show up on screen but still changes how the text behaves: zero-width spaces and joiners, non-breaking and other exotic spaces, soft hyphens, bidirectional control marks, byte order marks, and typographic lookalikes such as curly quotes and long dashes. Each finding is listed with its code point, its official Unicode name, and its position, and you choose which categories to clean rather than having everything rewritten for you. These characters arrive from word processors, PDFs, content management systems, and large language model output, where they break string comparisons, search, regular expressions, CSV imports, and code that looks correct on screen. Everything runs in your browser, so text you cannot paste into an online tool can still be checked here.",
  category: "text",
  keywords: [
    "remove zero width space",
    "invisible character detector",
    "hidden unicode characters",
    "clean pasted text",
    "remove smart quotes from text",
  ],
  tags: ["text", "unicode", "cleanup", "whitespace", "zero-width", "sanitize"],
  icon: ScanEye,
  features: [
    "Lists every hidden character with code point, name, and position",
    "Separate toggles for zero-width, spacing, control, and lookalike characters",
    "Shows the text with hidden characters marked so you can see where they are",
    "Reports how many of each character were found",
    "Copy or download the cleaned text",
    "Runs offline in your browser, so confidential text stays local",
  ],
  faqs: [
    {
      question: "Where do invisible characters in my text come from?",
      answer:
        "Common sources are word processors and content management systems that insert zero-width spaces as line break hints, PDFs that use soft hyphens, copy and paste from web pages, right-to-left text that carries bidirectional control marks, and text generated by large language models, which often contains non-breaking spaces and typographic quotes.",
    },
    {
      question: "What problems do these characters actually cause?",
      answer:
        "They break exact string comparison, so two values that look identical fail an equality check. They also break search and regular expressions, corrupt CSV and JSON imports, produce broken URL slugs and passwords, and cause code copied from a web page to fail with a confusing syntax error.",
    },
    {
      question: "Why are curly quotes and long dashes treated separately?",
      answer:
        "They are visible, not hidden, and in ordinary prose they are usually intentional. They are grouped as lookalikes because they break code, configuration files, and command lines when they replace a straight quote or hyphen, so you can convert them only when that is what you want.",
    },
    {
      question: "Is my text uploaded for analysis?",
      answer:
        "No. Detection and cleaning are done by JavaScript in your browser, and the text never leaves your device. That matters here because the text people most often need to check is text they cannot paste into a third party service.",
    },
  ],
  relatedTools: ["character-counter", "remove-duplicate-lines", "case-converter"],
}

export default meta
