/**
 * Writes src/lib/tool-index.generated.ts: the eagerly-loaded summary of
 * every tool's meta.ts.
 *
 * The registry used to eagerly glob every meta.ts, which put each tool's
 * longDescription, features, and faqs prose into the app entry chunk even
 * though only that tool's own page ever renders them. Generating a summary
 * keeps navigation, search, and category pages synchronous while leaving
 * the prose in a per-tool chunk. See decisions.md ADR-026.
 *
 * Runs automatically via the predev and prebuild npm scripts. The registry
 * cross-checks the generated file against the tool folders it discovers and
 * throws if the two disagree, so a stale file fails loudly rather than
 * silently dropping a tool.
 */
import fs from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"
import { format, resolveConfig } from "prettier"
import type { ToolMeta } from "../src/types/tool"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(__dirname, "..")
const toolsDir = path.join(root, "src/tools")
const outputPath = path.join(root, "src/lib/tool-index.generated.ts")

async function loadToolMetas(): Promise<ToolMeta[]> {
  const slugs = fs
    .readdirSync(toolsDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort()

  const metas: ToolMeta[] = []
  for (const slug of slugs) {
    const metaPath = path.join(toolsDir, slug, "meta.ts")
    if (!fs.existsSync(metaPath)) continue
    const mod = await import(`file://${metaPath.replace(/\\/g, "/")}`)
    metas.push(mod.default as ToolMeta)
  }
  return metas
}

function iconName(meta: ToolMeta): string {
  const name = (meta.icon as { displayName?: string }).displayName
  if (!name) {
    throw new Error(
      `Tool "${meta.slug}" uses an icon with no displayName. Tool icons must be lucide-react components.`,
    )
  }
  return name
}

function entrySource(meta: ToolMeta): string {
  const fields = [
    `slug: ${JSON.stringify(meta.slug)}`,
    `title: ${JSON.stringify(meta.title)}`,
    `description: ${JSON.stringify(meta.description)}`,
    `category: ${JSON.stringify(meta.category)}`,
    `keywords: ${JSON.stringify(meta.keywords)}`,
    `tags: ${JSON.stringify(meta.tags)}`,
    `icon: ${iconName(meta)}`,
  ]
  if (meta.isNew) fields.push("isNew: true")
  return `{ ${fields.join(", ")} }`
}

async function main() {
  const metas = await loadToolMetas()
  const icons = [...new Set(metas.map(iconName))].sort()

  const source = `// Generated by scripts/generate-tool-index.ts. Do not edit by hand.
// Run \`npm run generate:tool-index\` after adding, removing, or renaming a tool.
import { ${icons.join(", ")} } from "lucide-react"
import type { ToolSummary } from "@/types/tool"

export const toolIndex: ToolSummary[] = [
${metas.map((meta) => `  ${entrySource(meta)},`).join("\n")}
]
`

  const prettierConfig = await resolveConfig(outputPath)
  const formatted = await format(source, { ...prettierConfig, filepath: outputPath })
  fs.writeFileSync(outputPath, formatted)

  console.log(`Generated tool-index.generated.ts (${metas.length} tools).`)
}

main()
